# Generated by Django 4.2.1 on 2023-05-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_review_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
    ]
